"""Evaluation helpers for the Adaptive RAG project.

The evaluator provides simple deterministic metrics that are easy to reproduce
during grading. These metrics are intentionally lightweight and do not require
external model calls.
"""

from __future__ import annotations

import re
from collections import Counter


def normalize_text(text: str) -> str:
    """Normalize text for simple answer comparison."""
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return " ".join(text.split())


def token_overlap_score(predicted_answer: str, reference_answer: str) -> float:
    """Compute token overlap between predicted and reference answers.

    Returns a value from 0.0 to 1.0.
    """
    predicted_tokens = normalize_text(predicted_answer).split()
    reference_tokens = normalize_text(reference_answer).split()

    if not predicted_tokens or not reference_tokens:
        return 0.0

    predicted_counts = Counter(predicted_tokens)
    reference_counts = Counter(reference_tokens)

    overlap = sum(
        min(predicted_counts[token], reference_counts[token])
        for token in reference_counts
    )

    return round(overlap / len(reference_tokens), 4)


def exact_match(predicted_answer: str, reference_answer: str) -> bool:
    """Return True when normalized answers are exactly equal."""
    return normalize_text(predicted_answer) == normalize_text(reference_answer)


def evaluate_prediction(predicted_answer: str, reference_answer: str) -> dict:
    """Return basic evaluation metrics.

    Parameters
    ----------
    predicted_answer:
        Answer generated by the system.
    reference_answer:
        Expected answer used for local evaluation.

    Returns
    -------
    dict
        Evaluation metrics including exact_match and token_overlap.
    """
    return {
        "exact_match": exact_match(predicted_answer, reference_answer),
        "token_overlap": token_overlap_score(predicted_answer, reference_answer),
    }


def citation_present(citations: list[dict]) -> bool:
    """Return True when at least one citation is present."""
    return len(citations) > 0


def summarize_route_result(result: dict) -> dict:
    """Summarize one routed query response for benchmark reporting."""
    return {
        "complexity_label": result.get("complexity_label"),
        "strategy": result.get("strategy"),
        "retrieval_steps": result.get("retrieval_steps", 0),
        "latency_ms": result.get("latency_ms", 0),
        "citation_present": citation_present(result.get("citations", [])),
    }